### ISSUE TITLE
Additional Login Methods

### ISSUE THREAD

**Issue by Slyyxp** [Slyyxp/GeniePy#3]
Traceback (most recent call last):
  File "genie.py", line 169, in <module>
    client.auth()
  File "C:\GeniePy-master\modules\client.py", line 52, in auth
    raise exceptions.AuthenticationError("Authentication failed.")
modules.exceptions.AuthenticationError: Authentication failed.

why ? Im loggin via kakao

_Originally posted by @idfrann0 in https://github.com/Slyyxp/GeniePy/issues/1#issuecomment-929786642_

**Comment by Slyyxp** [comment]
GeniePy currently does not support any third-party login methods.
This means if you wish to utilize it you will need Genie credentials.

_Edit:_ I will keep this issue open and consider additional login methods

**Comment by Slyyxp** [comment]
I'm deciding not to work on this, if anyone is able to authenticate via Kakakotalk I am open to PR's.
